schoolproject/credentials/urls.py
from .import views
from django.urls import path
urlpatterns = [
    path('',views.home,name="home"),
    path('register', views.register, name="register"),
    path('login',views.login,name="login"),
    path('form',views.form,name="form"),
    path('submit_form',views.submit_form,name="submit_form"),
    path('logout',views.logout,name="logout"),

]

schoolproject/schoolapp/urls.py
from .import views
from django.urls import path
app_name='schoolapp'
urlpatterns = [
    path('',views.home,name="home"),
]

schoolproject/schoolproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schoolapp.urls')),
    path('credentials/', include('credentials.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schoolproject/credentials/models.py
from django.db import models

# Create your models here.
class Departments(models.Model):
    name=models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Courses(models.Model):
    name=models.CharField(max_length=250)
    department=models.ForeignKey(Departments,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Materials(models.Model):
    name=models.CharField(max_length=250)

    def __str__(self):
        return self.name

schoolproject/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import Departments,Courses,Materials

# Create your views here.
def home(request):
    return render(request,"home.html")
def register(request):
    if request.method== 'POST':
        username=request.POST['username']
        password=request.POST['password']
        password1=request.POST['password1']
        if password==password1:
            if User.objects.filter(username=username).exists():
                messages.info (request,'Username already taken')
                return redirect('register')
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save();
                return redirect('login')
        else:
            messages.info(request,'password not matching')
            return redirect('register')
        return redirect('/')
    return render(request,'register.html')

def login(request):
    if request.method== 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('form')
        else:
            messages.info(request,'invalid credentials')
            return redirect('login')
    return render(request,"login.html")
def form(request):
    if request.method == 'POST':
        selected_department_id = request.POST.get('department_id')
        if selected_department_id:
            courses = Courses.objects.filter(department_id=selected_department_id)
            data = {'courses': [{'id': course.id, 'name': course.name} for course in courses]}
            return JsonResponse(data)
        else:

            data = {'courses': []}
            return JsonResponse(data)
    else:
        departments = Departments.objects.all()
        materials = Materials.objects.all()
        return render(request, 'form.html', {'departments': departments, 'materials': materials})

def submit_form(request):
    purpose = request.POST.get('purpose', '')
    print("Received purpose:", purpose)
    if purpose == 'enquiry':
        message = 'Thank you for your Enquiry!'
    elif purpose == 'placeOrder':
        message = 'Your Order has been Placed Successfully!'
    elif purpose == 'returnOrder':
        message = 'Your Return Order has been Processed!'
    else:
        message = 'Thank you for your submission!'

    return render(request, 'order_confirm.html', {'message': message})


def logout(request):
    auth.logout(request)
    return redirect('/')

schoolproject/schoolapp/views.py
from django.shortcuts import render

from schoolapp import views

def home(request):
    return render(request, "home.html")

schoolproject/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
 <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>School Store</title>
    <style>
    #myForm {
      display: none;
    }


    #showFormButton {

    }
    </style>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{%  static 'assets/css/templatemo-grad-school.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">


  <!--header-->
   </head>
<header class="main-header clearfix" role="header">
    <div class="logo">
      <a href="#"><em>School</em> Store</a>
    </div>
    <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
    <nav id="menu" class="main-nav" role="navigation">
      <ul class="main-menu">
        <li><a href="{% url 'schoolapp:home' %}">Home</a></li>
      </ul>
    </nav>
  </header>
<body>
<section class="section coming-soon" data-section="section3">
<div class="container" style="text-align: center;">
    <div class="top-content">
        <h6 style="text-align:center">Please fill the form below</h6>
    </div>
<section class="section main-banner" id="top" data-section="section1">
      <video autoplay muted loop id="bg-video">
          <source src="{% static 'assets/images/course.jpg' %}" alt="">
      </video>

      <div class="video-overlay header-text">
          <div class="caption" alt="">
              <h6>School of Management</h6>
              <h2><em>Your</em> Classroom</h2>
               <h3 style="color: white;">Please Click here to fill the form</h3>
              <div class="main-button">
                <button onclick="toggleForm()" style=" padding: 20px 40px;font-size: 16px;cursor: pointer;background-color:orange;color: white;">Show Form</button>
              </div>
          </div>
      </div>
  </section>

    <form id="myForm" action="{% url 'submit_form' %}" method="POST">
        {% csrf_token %}
        <div class="col-md-12">
            <fieldset>
                <input type="text" class="form-control" id="name" placeholder="Name" required="">
            </fieldset>
        </div>
        <br>
        <div class="col-md-12">
            <fieldset>
                <input type="date" class="form-control" id="dob" placeholder="Date of Birth" required="">
            </fieldset>
        </div>
        <br>
        <div class="col-md-12">
            <fieldset>
                <input type="number" class="form-control" id="Age" placeholder="Age" required="">
            </fieldset>
        </div>
        <br>
        <div class="col-md-12">
            <fieldset>
                <select class="form-control" id="name" name="name" required="">
                    <option value="" disabled selected>Select your Gender</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Othes">Others</option>
                            <!-- Add more options as needed -->
                </select>
            </fieldset><br>
        </div>
        <div class="col-md-12">
            <fieldset>
                <input type="phonenumber" class="form-control" id="phonenumber" placeholder="Phone Number" required="">
            </fieldset>
        </div>
        <br>
        <div class="col-md-12">
            <fieldset>
                <input type="email" class="form-control" id="Email id" placeholder="Email id" required="">
            </fieldset>
        </div>
        <br>
        <div class="col-md-12">
            <fieldset>
                <input type="text" class="form-control" id="Address" placeholder="Address" required="">
            </fieldset>
        </div>
        <br>
        <div class="col-md-12">
            <fieldset>
                <select name="department_id" id="department_id" class="form-control">
                    <option value="">Select your Department</option>
                    {% for i in departments %}
                        <option value="{{ i.id }}">{{ i.name }}</option>
                    {% endfor %}
                </select>
                <br>
            </fieldset>
        </div>
        <br>
        <div class="col-md-12">
            <fieldset>
                <select name="course" id="course" class="form-control">
                    <option>Select Courses</option>
                        {% for i in courses %}
                        <option value="{{ i.id }}">{{ i.name }}</option>
                         {% endfor %}
                </select>
                <br>
            </fieldset>
         </div>
        <br>
        <div class="col-md-12">
            <fieldset>
            <select class="form-control" id="purpose" name="purpose" required="">
                    <option value="">Select your Purpose</option>
                    <option value="enquiry">For Enquiry</option>
                    <option value="placeOrder">Place Order</option>
                    <option value="returnOrder">Return Order</option>
            </select>
            </fieldset>
            <br>
         </div>
        <div class="col-md-12">
            <p style="color: white;font-size: 18px;">Materials:</p>
            {% for material in materials %}
                <div class="form-check form-check-inline" style="color: white;width:150px;">
                <input class="form-check-input" type="checkbox" name="materials" id="material_{{ material.id }}" value="">
                <label class="form-check-label" for="material_{{ material.id }}">{{ material.name }}</label>
                </div>
            {% endfor %}
         </div>
        <br>
        <div class="col-md-12">
            <fieldset>
                <button type="submit" id="form-submit" class="Submit" >Submit</button>
            </fieldset>
        </div>
</div>
    </form>
   <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    function toggleForm() {
      var form = document.getElementById("myForm");
      form.style.display = (form.style.display === "none") ? "block" : "none";
    }
    $(document).ready(function() {
        // Function to handle the change event on the department dropdown
        $('#department_id').change(function() {
            var departmentId = $(this).val();

            // Make an AJAX request to fetch courses based on the selected department
            $.ajax({
                type: 'POST',
                url: '{% url "form" %}',
                data: {
                    'department_id': departmentId,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(data) {
                    var coursesDropdown = $('#course');
                    coursesDropdown.empty();

                    // Populate the courses dropdown with the retrieved data
                    $.each(data.courses, function(index, course) {
                        coursesDropdown.append($('<option>').val(course.id).text(course.name));
                    });
                },
                error: function(xhr, status, error) {
                    console.error('AJAX error:', status, error);
                }
            });
        });

      });
</script>
</section>

</body>
<footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
            <p><i class="fa fa-copyright"></i> Copyright 2024 by School Store</p></div>
      </div>
    </div>
  </footer>
</html>

schoolproject/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>School Store</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{%  static 'assets/css/templatemo-grad-school.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">
<!--

TemplateMo 557 Grad School

https://templatemo.com/tm-557-grad-school

-->
  </head>

<body>


  <!--header-->
  <header class="main-header clearfix" role="header">
    <div class="logo">
      <a href="#"><em>School</em> Store</a>
    </div>
    <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
    <nav id="menu" class="main-nav" role="navigation">
      <ul class="main-menu">
        <li><a href="{% url 'schoolapp:home' %}">Home</a></li>
          {% if user.is_authenticated %}
        <li style="color:white;text-align:center;">WELCOME {{ user.username }}</li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
    {% else %}
        <li><a href="{% url 'register' %}">Register</a></li>
        <li><a href="{% url 'login' %}">Login</a></li>
        <li class="has-submenu"><a href="">Departments</a>
        <ul class="sub-menu">
        <li><a href="https://en.m.wikipedia.org/wiki/Bachelor_of_Science">B.SC</a></li>
        <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Technology">B.TECH</a></li>
        <li><a href="https://en.m.wikipedia.org/wiki/Bachelor_of_Arts">BA</a></li>
        <li><a href="https://en.m.wikipedia.org/wiki/Bachelor_of_Commerce">B.COM</a></li>
        <li><a href="https://en.m.wikipedia.org/wiki/Bachelor_of_Business_Administration">BBA</a></li>

        </ul>
        </li>
    {% endif %}
    </ul>
    </nav>
  </header>

  <!-- ***** Main Banner Area Start ***** -->
  <section class="section main-banner" id="top" data-section="section1">
      <video autoplay muted loop id="bg-video">
          <source src="{% static 'assets/images/course.jpg' %}" alt="">
      </video>

      <div class="video-overlay header-text">
          <div class="caption">
              <h6>School of Management</h6>
              <h2><em>Your</em> Classroom</h2>
              <div class="main-button">
                  <div class="scroll-to-section"><a href="{% url 'login' %}">Discover More</a></div>
              </div>
          </div>
      </div>
  </section>
  <!-- ***** Main Banner Area End ***** -->


  <section class="features">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-12">
          <div class="features-post">
            <div class="features-content">
              <div class="content-show">
                <h4><i class="fa fa-pencil"></i>All Courses</h4>
              </div>
              <div class="content-hide">
                <p>Curabitur id eros vehicula, tincidunt libero eu, lobortis mi. In mollis eros a posuere imperdiet. Donec maximus elementum ex. Cras convallis ex rhoncus, laoreet libero eu, vehicula libero.</p>
                <p class="hidden-sm">Curabitur id eros vehicula, tincidunt libero eu, lobortis mi. In mollis eros a posuere imperdiet.</p>
                <div class="scroll-to-section"><a href="#section2">More Info.</a></div>
            </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-12">
          <div class="features-post second-features">
            <div class="features-content">
              <div class="content-show">
                <h4><i class="fa fa-graduation-cap"></i>Virtual Class</h4>
              </div>
              <div class="content-hide">
                <p>Curabitur id eros vehicula, tincidunt libero eu, lobortis mi. In mollis eros a posuere imperdiet. Donec maximus elementum ex. Cras convallis ex rhoncus, laoreet libero eu, vehicula libero.</p>
                <p class="hidden-sm">Curabitur id eros vehicula, tincidunt libero eu, lobortis mi. In mollis eros a posuere imperdiet.</p>
                <div class="scroll-to-section"><a href="#section3">Details</a></div>
            </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-12">
          <div class="features-post third-features">
            <div class="features-content">
              <div class="content-show">
                <h4><i class="fa fa-book"></i>Real Meeting</h4>
              </div>
              <div class="content-hide">
                <p>Curabitur id eros vehicula, tincidunt libero eu, lobortis mi. In mollis eros a posuere imperdiet. Donec maximus elementum ex. Cras convallis ex rhoncus, laoreet libero eu, vehicula libero.</p>
                <p class="hidden-sm">Curabitur id eros vehicula, tincidunt libero eu, lobortis mi. In mollis eros a posuere imperdiet.</p>
                <div class="scroll-to-section"><a href="#section4">Read More</a></div>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="section why-us" data-section="section2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="section-heading">
            <h2>Why choose This School?</h2>
          </div>
        </div>
        <div class="col-md-12">
          <div id='tabs'>
            <ul>
              <li><a href='#tabs-1'>Best Education</a></li>
              <li><a href='#tabs-2'>Top Management</a></li>
              <li><a href='#tabs-3'>Quality Meeting</a></li>
            </ul>

          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="section coming-soon" data-section="section3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="continer centerIt">
            <div>
              <h4>Take <em>any online course</em> and win $326 for your next class</h4>
              <div class="counter">

                <div class="days">
                  <div class="value">00</div>
                  <span>Days</span>
                </div>

                <div class="hours">
                  <div class="value">00</div>
                  <span>Hours</span>
                </div>

                <div class="minutes">
                  <div class="value">00</div>
                  <span>Minutes</span>
                </div>

                <div class="seconds">
                  <div class="value">00</div>
                  <span>Seconds</span>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="section contact" data-section="section6">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="section-heading">
            <h2>Let’s Keep In Touch</h2>
          </div>
        </div>
        <div class="col-md-6">

        <!-- Do you need a working HTML contact-form script?

                    Please visit https://templatemo.com/contact page -->

          <form id="contact" action="" method="post">
            <div class="row">
              <div class="col-md-6">
                  <fieldset>
                    <input name="name" type="text" class="form-control" id="name" placeholder="Your Name" required="">
                  </fieldset>
                </div>
                <div class="col-md-6">
                  <fieldset>
                    <input name="email" type="text" class="form-control" id="email" placeholder="Your Email" required="">
                  </fieldset>
                </div>
              <div class="col-md-12">
                <fieldset>
                  <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your message..." required=""></textarea>
                </fieldset>
              </div>
              <div class="col-md-12">
                <fieldset>
                  <button type="submit" id="form-submit" class="button">Send Message Now</button>
                </fieldset>
              </div>
            </div>
          </form>
        </div>
        <div class="col-md-6">
          <div id="map">
            <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="422px" frameborder="0" style="border:0" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
  </section>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
            <p><i class="fa fa-copyright"></i> Copyright 2024 by School Store</p></div>
      </div>
    </div>
  </footer>

  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <script src="{% static 'assets/js/isotope.min.js' %}"></script>
    <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
    <script src="{% static 'assets/js/lightbox.js' %}"></script>
    <script src="{% static 'assets/js/tabs.js' %}"></script>
    <script src="{% static 'assets/js/video.js' %}"></script>
    <script src="{% static 'assets/js/slick-slider.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
</body>
</html>

schoolproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>School Store</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{%  static 'assets/css/templatemo-grad-school.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">
<!--

TemplateMo 557 Grad School

https://templatemo.com/tm-557-grad-school

-->
  </head>
  <!--header-->
  <header class="main-header clearfix" role="header">
    <div class="logo">
      <a href="#"><em>School</em> Store</a>
    </div>
    <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
    <nav id="menu" class="main-nav" role="navigation">
      <ul class="main-menu">
        <li><a href="{% url 'schoolapp:home' %}">Home</a></li>
      </ul>
    </nav>
  </header>

  </head>
<body>

  <section class="section coming-soon" data-section="section3">
    <div class="container" style="text-align: center;">

            <div class="top-content">
              <h6 style="text-align:center">Login here to see more details</h6>
            </div>
            <div style="color:white">
                {% for msg in messages %}
                {{ msg }}
                {% endfor %}
            </div>
            <form id="contact" action="" method="POST">
                {% csrf_token %}
                <div class="col-md-12">
                  <fieldset>
                    <input type="text" name="username" class="form-control" id="username" placeholder="User name" required="">
                  </fieldset>
                </div>
                <div class="col-md-12">
                  <fieldset>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password" required="">
                  </fieldset>
                </div>
                <div class="col-md-12">
                  <fieldset>
                      <button type="submit" id="form-submit" class="Submit"><a href="">Submit</a></button>
                      <fieldset>
                      <h6 style="color:white;">If you're a new user,Please click here to register</h6>
                    <div class="col-md-12">
                     <li><a href="{% url 'register' %}">Register</a></li>
                    </div>
                  </fieldset>
                  </fieldset>



                </div>
            </form>

        </div>

  </section>
<footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
            <p><i class="fa fa-copyright"></i> Copyright 2024 by School Store</p></div>
      </div>
    </div>
  </footer>
</body>
</html>

schoolproject/templates/order_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>School Store</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{%  static 'assets/css/templatemo-grad-school.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">
<!--

TemplateMo 557 Grad School

https://templatemo.com/tm-557-grad-school

-->
  </head>
  <!--header-->
  <header class="main-header clearfix" role="header">
    <div class="logo">
      <a href="#"><em>School</em> Store</a>
    </div>
    <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
    <nav id="menu" class="main-nav" role="navigation">
      <ul class="main-menu">
        <li><a href="{% url 'home' %}">Home</a></li>
      </ul>
    </nav>
  </header>

  </head>
<body>
 <section class="section main-banner" id="top" data-section="section1">
      <video autoplay muted loop id="bg-video">
          <source src="{% static 'assets/images/course.jpg' %}" alt="">
      </video>

      <div class="video-overlay header-text">
          <div class="caption">
              <h6>Graduate School of Management</h6>
              <body>
                {% if message %}
                    <h3>{{ message }}</h3>
                {% endif %}
              </body>
              <div class="main-button">
                  <div class="scroll-to-section"><a href="{% url 'schoolapp:home' %}">BACK TO HOME</a></div>
              </div>
          </div>
      </div>
  </section>
<footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
            <p><i class="fa fa-copyright"></i> Copyright 2024 by School Store</p></div>
      </div>
    </div>
  </footer>
</body>
</html>

schoolproject/templates/register.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>School Store</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{%  static 'assets/css/templatemo-grad-school.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">
<!--

TemplateMo 557 Grad School

https://templatemo.com/tm-557-grad-school

-->
  </head>
  <!--header-->
  <header class="main-header clearfix" role="header">
    <div class="logo">
      <a href="#"><em>School</em> Store</a>
    </div>
    <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
    <nav id="menu" class="main-nav" role="navigation">
      <ul class="main-menu">
        <li><a href="{% url 'schoolapp:home' %}">Home</a></li>
      </ul>
    </nav>
  </header>

  </head>
<body>
  <section class="section coming-soon" data-section="section3">
    <div class="container" style="text-align: center;">

            <div class="top-content">
              <h6 style="text-align:center">Register your free account and <em>get immediate</em> access to courses</h6>
            </div>
            <div style="color:white">
                {% for msg in messages %}
                {{ msg }}
                {% endfor %}
            </div>
        <form id="contact" action="" method="POST">
            {% csrf_token %}
                <div class="col-md-12">
                  <fieldset>
                    <input type="name" name="username" class="form-control" id="name" placeholder="User name" required="">
                  </fieldset>
                </div>
                <div class="col-md-12">
                  <fieldset>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Enter your password" required="">
                  </fieldset>
                </div>
                <div class="col-md-12">
                  <fieldset>
                    <input type="password" name="password1" class="form-control" id="password" placeholder="Confirm  password" required="">
                  </fieldset>
                </div>
                <div class="col-md-12">
                  <fieldset>
                    <button type="submit" id="form-submit" class="Submit" href="{% url 'login' %}">Submit</button>
                      <fieldset>
                      <h6 style="color:white;">Already registered,Login here</h6>
                    <div class="col-md-12">
                     <li><a href="{% url 'login' %}">Login</a></li>
                    </div>
                  </fieldset>
                  </fieldset>
            </form>
        </div>

  </section>

<footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
            <p><i class="fa fa-copyright"></i> Copyright 2024 by School Store</p></div>
      </div>
    </div>
  </footer>
</body>
</html>